name: app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [app]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure Remote Driver
        run: |
          docker buildx create \
          --name remote        \
          --driver remote      \
          tcp://buildkitd:1234
      - name: Build Docker Image
        run: |
          docker buildx build --builder=remote -t test .
