name: app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install BuildKit CLI
        run: |
          wget https://github.com/moby/buildkit/releases/download/v0.9.0/buildkit-v0.9.0.linux-amd64.tar.gz
          tar xvf buildkit-v0.9.0.linux-amd64.tar.gz
      - name: Build Docker Image
        run: |
          ./bin/buildctl --addr tcp://buildkitd.builders.svc.cluster.local:1234 build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=simple
